---
title: "Functional programming Lab 1"
author: "Meghan Siritzky, Lea Frank, Wanjia Guo, and Sarah Dimakis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1. From the model results: Extract the qr tolerance (tol). Extract the term labels from the model.

```{r}
set.seed(123) # Set random number generation

m <- lm(mpg ~ hp + cyl + drat, mtcars)

l <- list(a = list(m = matrix(1:12, ncol = 3),
              	   v = 1:7),
          b = data.frame(student = 1:15,
                         score = rnorm(15, 100, 10)))

# From the model results: Extract the qr tolerance (tol).
qr(m)$tol

# Extract the term labels from the model.
model <- attributes(m$model)
terms <- attributes(model$terms)
terms$term.labels
```

3. Use the “airquality” dataset, which is part of base R. Split it by `Month`

```{r}
by_month <- split(airquality, airquality$Month)

str(by_month)
```

4. Use a for loop to calculate the mean Ozone by month (remember to remove missing data from the calculation)

```{r}
mean_ozone <- rep(NA, length(by_month))

for (i in seq_along(by_month)) {
  mean_ozone[i] <- mean(by_month[[i]]$Ozone, na.rm = TRUE)
}

mean_ozone
```