---
title: "Functional programming Lab 2"
author: "Meghan Siritzky, Lea Frank, Wanjia Guo, and Sarah Dimakis"
output: 
  html_document: 
    toc: yes
    toc_float: yes
    theme: yeti
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(repurrrsive)
library(kableExtra)
```

# Part A: Multiple Models

```{r}
file <- "https://github.com/datalorax/esvis/raw/master/data/benchmarks.rda"
load(url(file))
head(benchmarks)

benchmarks <- benchmarks %>%
	as_tibble() %>%
	mutate(wave = case_when(season == "Fall" ~ 0,
	                        season == "Winter" ~ 1,
	                        TRUE ~ 2))

# Fit a model of the form lm(math ~ wave) for each student.
by_student <- benchmarks %>% 
  group_by(sid) %>%
  filter(n() >= 3) %>% # excluding students with only 1 or 2 datapoint from regression.
  split(., .$sid)
math_mods <- map(by_student, ~lm(math ~ wave, data = .x))

# Plot the distribution of slopes. Annotate the plot with a vertical line for the mean.
coefs <- map(math_mods, coef)
#coefs[c(1:2, length(coefs))]

slopes <- map_dbl(coefs, 2)

sdist <- tibble(sid = names(slopes),
                   slope = slopes)
slope_mean <- mean(sdist$slope, na.rm=TRUE)

ggplot(sdist, aes(slope)) +
    geom_histogram(fill = "lightblue",
                   color = "white",
                   bins = 30) +
  geom_vline(xintercept = slope_mean)

```

# Part B: Star Wars

```{r}

characters <- map_dbl(sw_films, ~length(.x[["characters"]])) #extract number of characters

titles <- map_chr(sw_films, ~.x[["title"]]) #extract titles

tibble(Title = titles,
    `Number of characters` = characters) %>% 
  kbl(caption = "The number of characters in each film.") %>% 
  kable_styling(bootstrap_options = c("striped", "hover"), full_width = FALSE, position = "left")

```


```{r}
hair_colors<- map_chr(sw_species, ~.x[["hair_colors"]]) #extract hair colors

names <- map_chr(sw_species, ~.x[["name"]]) #extract names

hair_colors_table <- tibble(Name = names,
    `Hair color` = hair_colors) %>% 
  filter(!`Hair color` %in% c("unknown", "n/a"))

hair_colors_table %>% kbl(caption = "All of the species that have known hair colors, including species that are hairless (none).") %>% 
  kable_styling(bootstrap_options = c("striped", "hover"), full_width = FALSE) %>% 
    scroll_box(width = "350px", height = "400px")

```

<br>

```{r}
hair_colors_table["Hair color"] %>% unique() %>% 
  kbl(caption = "All of the hair colors.") %>% 
  kable_styling(bootstrap_options = c("striped", "hover"), full_width = FALSE, position = "left")

```


# Part C: Some basic API calls


```{r}
library(httr)

# starting with vector of 1:5
abilities <- c(1:5)

# generating paths to the API's
pokemon_df = map(abilities, ~{str_c("https://pokeapi.co/api/v2/ability/", .x)}) %>% 
  map(~{GET(.x) %>% content("parsed")})

abilities <-  pokemon_df %>% 
  map_dfr(~{
    tibble(ability = .x$name, num_pokemon = length(.x$pokemon))
  })

abilities %>% 
  kbl(caption = "First five abilities and the number of pokemon with that ability.") %>% 
  kable_styling(bootstrap_options = c("striped", "hover"), 
                full_width = FALSE, 
                position = "left")
```

# Bonus

```{r}

pokemon = pokemon_df %>% 
  map_dfr(~{
    tibble(ability = .x$name, 
           pokemon = .x$pokemon %>% 
             map_chr(~.x[['pokemon']][['name']]))
  })
  
pokemon[,2] %>% 
  kbl(caption = "First five abilities and the pokemon with that ability.") %>% 
  pack_rows(index = table(fct_inorder(pokemon$ability))) %>% 
  kable_styling(bootstrap_options = c("striped", "hover"), 
                full_width = FALSE, position = "left") %>% 
  scroll_box(width = "250px", height = "400px")

```

