---
title: "Functional programming Midterm"
author: "Meg Siritzky, Lea Frank, Wanjia Guo, and Sarah Dimakis"
output: 
  html_document: 
    toc: yes
    toc_float: yes
    theme: yeti
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = TRUE)

library(tidyverse)
library(repurrrsive)
library(kableExtra)
library(rio)
library(glue)
library(dplyr)
#remotes::install_github("datalorax/gapr")
library(gapr)
```

# Part A (1) 

```{r}
download_file <- function(year) {
  link <- glue::glue("https://www.oregon.gov/ode/educator-resources/assessment/TestResults20{year}/pagr_schools_ela_raceethnicity_{year-1}{year}.xlsx")
  rio::import(link, setclass = "tibble", na = c("-", "--", "*"))
}

school_raw <- map_dfr(15:18, download_file)
```

```{r}
school_clean <- school_raw %>% 
  janitor::clean_names() %>% 
  filter(student_group == "White" |
           student_group == "Hispanic/Latino") %>% 
  pivot_longer(cols = c(number_level_1, number_level_2, number_level_3, number_level_4), names_to = "level", values_to = "n") %>% 
  mutate(level = recode(level, number_level_1 = "1"),
         level = recode(level, number_level_2 = "2"),
         level = recode(level, number_level_3 = "3"),
         level = recode(level, number_level_4 = "4")) %>% 
  dplyr::select(academic_year, district, school, student_group, grade_level, level, n) %>% 
  drop_na(n)
```

# Part A (2)

```{r}
school <- school_clean %>% 
  group_by(district) %>%
  mutate(n_schools = length(unique(school))) %>% 
  group_by(academic_year, district, level, student_group, n_schools) %>%
  summarize(n = sum(n)) %>% 
  pivot_wider(names_from = student_group, values_from = n) %>% 
  janitor::clean_names() %>% 
  drop_na(hispanic_latino, white) %>% 
  arrange(district) 

```

# Part B (1)

```{r warning=FALSE}
school_map <- school %>% 
  group_by(district) %>% 
  nest() %>% 
  mutate(estv_map = map(data, ~estimate_v(data = .x, "white", "hispanic_latino")))

school_row <- school %>% 
  ungroup() %>% 
  nest_by(district) %>% 
  summarize(estv_row = list(estimate_v(data, "white", "hispanic_latino")))

school_plot <- left_join(school_map, school_row)
```

# Part B (2)

```{r}
# not all models, unsure why
# filtered out those models to compare estimates
school_plot <- school_plot %>% 
  mutate(isnull_map = map_lgl(estv_map, ~ nrow(.x)==0),
         isnull_row = map_lgl(estv_row, ~ nrow(.x)==0)) %>% 
  filter(!isnull_map | !isnull_row) %>% 
  mutate(v_map = map_dbl(estv_map, "v"),
         v_row = map_dbl(estv_row, "v"))

school_plot %>% 
  ggplot(aes(x = v_map, y = v_row)) + 
  geom_point(alpha = .5) +
  geom_line(color = "cadetblue") +
  labs(x = "Estimates from Purrr Method", 
       y = "Estimates from Rowwise Method") +
  theme_minimal()
```

# Part B (3)

```{r}
dists <- unique(school$district)[1:10]

school_nestby = school %>% 
  ungroup() %>% 
  filter(district %in% dists) %>% 
  mutate(academic_year = factor(academic_year)) %>% 
  nest_by(academic_year, district, n_schools) %>% 
  mutate(estv_map = list(estimate_v(data, "white", "hispanic_latino")),
         mean = list(estv_map$v[1]) %>% as.numeric(),
         se = list(estv_map$v_se[1]) %>% as.numeric(),
         ci = list(se * 1.96) %>% as.numeric(),
         pos_neg = list(mean >= 0) %>% as.factor()) %>% 
  select(-c(data, estv_map)) %>%
  ungroup() %>% 
  nest_by(district, n_schools) %>% 
  mutate(
    district_name = str_replace_all(
             district,
             " (SD.+)", 
             " School District"),
    nestby_plot = list(
  ggplot(data, 
         aes(academic_year, mean)) + 
    geom_hline(yintercept = 0, color = 'red') +
    geom_line(aes(group = 1)) +
    geom_errorbar(aes(ymin = mean-ci, ymax = mean+ci), width = 0.2) +
    geom_point(aes(color = pos_neg), size=2) + 
    theme_minimal() + 
    scale_color_brewer(palette="Accent") +
    labs(x = 'School year',
         y = 'Average achievement difference (SD units)',
         title = glue('Achievement Gap Estimates: {district_name}'),
         subtitle = "Negative values indicate 
         <span style = 'color: #55B190'>**White**</span> 
         students have higher average achievement<br>
         Positive values indicate
         <span style = 'color: #887E96'>**Hispanic/Latino**</span> 
          students have higher average achievement",
         caption = glue('Note: District included {n_schools} schools.')) +
    theme(legend.position = 'none',
          plot.subtitle = ggtext::element_markdown())
))
  
school_nestby$nestby_plot[8]

```

```{r}

school_nest = school %>% 
  ungroup() %>% 
  filter(district %in% dists) %>% 
  group_by(academic_year, district, n_schools) %>% 
  nest() %>% 
  mutate(estv_map = map(data,estimate_v, "white", "hispanic_latino")) %>% 
  unnest(estv_map) %>% 
  select(-data) %>% 
  mutate(pos_neg = (v >= 0),
         ci = v_se * 1.96,
         district_name = str_replace_all(
             district,
             " (SD.+)", 
             " School District")) %>% 
  group_by(district_name, n_schools) %>% 
  nest() %>% 
  mutate(nest_plot = pmap(list(data,
                          district_name,
                          n_schools),
                     ~{
      ggplot(..1, aes(academic_year, v)) + 
    geom_hline(yintercept = 0, color = 'red') +
    geom_line(aes(group = 1)) +
    geom_errorbar(aes(ymin = v-ci, ymax = v+ci), width = 0.2) +
    geom_point(aes(color = pos_neg), size=2) + 
    theme_minimal() + 
    scale_color_brewer(palette="Accent") +
    labs(x = 'School year',
         y = 'Average achievement difference (SD units)',
         title = glue('Achievement Gap Estimates: {..2}'),
         subtitle = "Negative values indicate 
         <span style = 'color: #55B190'>**White**</span> 
         students have higher average achievement<br>
         Positive values indicate
         <span style = 'color: #887E96'>**Hispanic/Latino**</span> 
          students have higher average achievement",
         caption = glue('Note: District included {..3} schools.')) +
    theme(legend.position = 'none',
          plot.subtitle = ggtext::element_markdown())
  }))
  
school_nest$nest_plot[8]

```

# Part B (3): Extra Credit

```{r warning = FALSE, fig.height = 4, fig.width = 15}
school_combine = inner_join(school_nest %>% select(-data), 
           school_nestby %>% select(-c(district, data))) %>% 
  rowwise() %>% 
  mutate(
  combine_plot = list(cowplot::plot_grid(nestby_plot, 
                                         nest_plot, 
                                         labels = c('Nestby', 'Nest'),
                                         label_x = 0, 
                                         label_y = 0,
                                         hjust = -0.5, 
                                         vjust = -0.5)))

school_combine$combine_plot[8]
```